### ISSUE TITLE
minSdk < 21的话就集成不了了

### ISSUE THREAD

**Issue by fgb3420** [yellowcath/VideoProcessor#11]
minSdk为19，gradle里面implementation失败了，日志如下：

uses-sdk:minSdkVersion 19 cannot be smaller than version 21 declared in library [com.github.yellowcath:VideoProcessor:2.3.3] C:\Users\Fgb\.gradle\caches\transforms-1\files-1.1\VideoProcessor-2.3.3.aar\31435ecdb022228d8ca0f9a0ca396e39\AndroidManifest.xml as the library might be using APIs not available in 19
	Suggestion: use a compatible library with a minSdk of at most 19,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.hw.videoprocessor" to force usage (may lead to runtime failures)

看了下VideoProcessor的gradle发现minSdk是21，有办法兼容下吗

**Comment by yellowcath** [comment]
可以试一下，但是我没低版本的机器测试，不知道能不能用
implementation 'com.github.yellowcath:VideoProcessor:2.3.3-api18'
