### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by VineshChauhan24** [yellowcath/VideoProcessor#13]
throwing exception when mixing audio file to video , audio file is stored in sdcard. exception is only thworing on some devices.

02-14 12:10:32.269 24952-24952/com.hw.photomovie W/System.err: java.lang.IllegalArgumentException
02-14 12:10:32.269 24952-24952/com.hw.photomovie W/System.err:     at android.media.MediaExtractor.readSampleData(Native Method)
02-14 12:10:32.269 24952-24952/com.hw.photomovie W/System.err:     at com.hw.videoprocessor.VideoProcessor.mixAudioTrack(VideoProcessor.java:864)
02-14 12:10:32.269 24952-24952/com.hw.photomovie W/System.err:     at com.hw.photomovie.sample.DemoPresenter$5.onRecordFinish(DemoPresenter.java:465)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at record.GLMovieRecorder$1$1$1.run(GLMovieRecorder.java:92)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at android.os.Looper.loop(Looper.java:148)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5451)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-14 12:10:32.270 24952-24952/com.hw.photomovie W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by yellowcath** [comment]
plz update to photomovie 1.6.3 
[https://github.com/yellowcath/PhotoMovie#160](https://github.com/yellowcath/PhotoMovie#160)
