### ISSUE TITLE
Surface 与 原始视频数据获取问题？

### ISSUE THREAD

**Issue by xjhh** [yellowcath/VideoProcessor#18]
有没有办法 在使用surface的情况下 解码  获取原始视频数据后进行处理 返回数据渲染至编码surface呢？

**Comment by yellowcath** [comment]
这个是可行的，就是写起来挺复杂的，要给解码surface绑个纹理，然后绘到自己的离屏环境，然后一系列GL处理，最后把整个fbo绘到编码surface
