### ISSUE TITLE
Project processing video failed

### ISSUE THREAD

**Issue by wd574998820** [yellowcath/VideoProcessor#2]
I am currently getting the following error:
04-19 17:26:04.698 24523-24638/com.hw.videoprocessor E/WVMExtractor: Failed to open libwvm.so: dlopen failed: library "libwvm.so" not found
04-19 17:26:07.441 24523-24644/com.hw.videoprocessor I/OMXClient: MuxOMX ctor
04-19 17:26:07.466 24523-24644/com.hw.videoprocessor E/ACodec: [OMX.qcom.video.encoder.avc] storeMetaDataInBuffers (output) failed w/ err -1010
04-19 17:26:07.467 24523-24644/com.hw.videoprocessor W/ACodec: do not know color format 0x7fa30c04 = 2141391876
04-19 17:26:07.468 24523-24644/com.hw.videoprocessor W/ACodec: do not know color format 0x7f000789 = 2130708361
04-19 17:26:07.495 24523-24644/com.hw.videoprocessor I/ACodec: setupAVCEncoderParameters with [profile: Baseline] [level: Level51]
04-19 17:26:07.497 24523-24644/com.hw.videoprocessor E/ACodec: [OMX.qcom.video.encoder.avc] configureCodec returning error -1010
04-19 17:26:07.497 24523-24644/com.hw.videoprocessor E/ACodec: signalError(omxError 0x80001001, internalError -1010)
04-19 17:26:07.498 24523-24643/com.hw.videoprocessor E/MediaCodec: Codec reported err 0xfffffc0e, actionCode 0, while in state 3
04-19 17:26:07.498 24523-24641/com.hw.videoprocessor E/MediaCodec: configure failed with err 0xfffffc0e, resetting...
04-19 17:26:07.506 24523-24644/com.hw.videoprocessor I/OMXClient: MuxOMX ctor
04-19 17:26:07.533 24523-24641/com.hw.videoprocessor E/MediaCodec: android.media.MediaCodec$CodecException: Error 0xfffffc0e
                                                                       at android.media.MediaCodec.native_configure(Native Method)
                                                                       at android.media.MediaCodec.configure(MediaCodec.java:1884)
                                                                       at com.hw.videoprocessor.VideoEncodeThread.doEncode(VideoEncodeThread.java:95)
                                                                       at com.hw.videoprocessor.VideoEncodeThread.run(VideoEncodeThread.java:67)

I am currently testing under the following environment:

OS name: Android
OS version: 7.1.2
Model: Nexus 6P

**Comment by yellowcath** [comment]
this error means not support odd encode odd size video
I fixed it

**Comment by EternalPlan** [comment]
同一个文件 多次压缩之后  依旧会报这个错误
