### ISSUE TITLE
希望提供arm64-v8a 版本的SO包

### ISSUE THREAD

**Issue by masterTail** [yellowcath/VideoProcessor#20]
你好！大佬，我看了一下你的的库，在armeabi-v7a文件下有提供声音处理库，但是没有提供arm64-v8a版本的so库，希望完善一下，谢谢

**Comment by 337240552** [comment]
可以自己编

**Comment by yellowcath** [comment]
https://gitlab.com/soundtouch/soundtouch
这里是源码

**Comment by masterTail** [comment]
> https://gitlab.com/soundtouch/soundtouch
> 这里的英文源码

好的谢谢
