### ISSUE TITLE
AndroidQ压缩文件时报错

### ISSUE THREAD

**Issue by wuyang049679** [yellowcath/VideoProcessor#42]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.hc_android.hc_css-e2V6zxpyAL14GvCnDlqGxg==/base.apk"],nativeLibraryDirectories=[/data/app/com.hc_android.hc_css-e2V6zxpyAL14GvCnDlqGxg==/lib/x86, /data/app/com.hc_android.hc_css-e2V6zxpyAL14GvCnDlqGxg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libsoundtouch.so"

**Comment by yellowcath** [comment]
之前缺了arm64的so，已经补上了
com.github.yellowcath:VideoProcessor:2.4.1
