### ISSUE TITLE
关于设置特殊前缀信息的一些疑点

### ISSUE THREAD

**Issue by ice-coffee** [yellowcath/VideoProcessor#50]
您好，我在看您的项目时，发现关于设置特殊前缀信息这一块有些问题希望能和您探讨一下：

在VideoProcessor.mixAudioTrack方法中您对通过Extrator.getTrackFormat方法获得的MediaFormat对象设置了特殊前缀设置信息，但是在google的官方文档中有如下一句话：

>These keys are always included in the track MediaFormat obtained from the MediaExtractor#getTrackFormat. Codec-specific data in the format is automatically submitted to the codec upon start(); you MUST NOT submit this data explicitly.

这说明如果通过Extrator.getTrackFormat方法获取的MediaFormat对象是不需设置前缀信息的，而且在mixAudioTrack方法中注释掉相关设置代码后运行依旧正常，关于这个问题您能说明一下吗，太感谢了 ^_^

如果可以的话您能讲解一下
`audioMediaFormat.setByteBuffer("csd-0", csd);`
中csd的值为什么这么生成吗，感谢感谢 ^_^

**Comment by yellowcath** [comment]
自己录制的话是不需要的，好像是为了从pcm转换格式的时候，需要自己补
