### ISSUE TITLE
java.lang.IllegalStateException: Failed to stop the muxer

### ISSUE THREAD

**Issue by yueshiwei** [yellowcath/VideoProcessor#6]
oppo r9s `手机将flv，avi，mkv，webm4种格式的视频转成MP4格式的视频，都报错，怎么解决呢？其他手机没问题

**Comment by yellowcath** [comment]
因为MediaCodec是完全依赖系统的，可能是这个手机没提供相应的解码器？
验证的话可以断点看一下VideoDecodeThread.doDecode()里面MediaCodec.createDecoderByType()是不是报错了
如果视频没问题的话也有可能是音频，AudioUtil.writeAudioTrackDecode（）,同样看里面的MediaCodec.createDecoderByType()是不是报错了
