### ISSUE TITLE
how can i cancel process

### ISSUE THREAD

**Issue by uannia** [yellowcath/VideoProcessor#8]
Pls help me cancel process , thanks you !!!

**Comment by yellowcath** [comment]
There's no such method，you can run it in a new thread and ignore it's result

**Comment by uannia** [comment]
i only use reverse video from your lib, can i run it in min sdk 18 ?

**Comment by yellowcath** [comment]
you can try this:
implementation 'com.github.yellowcath:VideoProcessor:2.3.3-api18'
But I don't have the proper machine to test.

**Comment by yellowcath** [comment]
pls tell me if it worked correctly

**Comment by uannia** [comment]
it seem not work ,output video only have audio , but it still the best lib for edit video ,tks u.
