### ISSUE TITLE
完全不能用啊 

### ISSUE THREAD

**Issue by AimersCat** [yellowcath/VideoProcessor#9]
选择一个大一点的视频直接就压缩不了了  然后小一点的压了一点就压不了了

**Comment by yellowcath** [comment]
你好，能提供更详细一点的信息么？比如压缩不了是否报错，错误信息是什么，出错的机型。
大的视频压缩不了可能是分辨率过大，比如4k的视频，因为硬解码压缩通过GPU的，在压缩的时候GPU无法处理这么大的尺寸的视频流会直接crash
小的视频能压多少是看你提供的bitrate参数，如果你指的是demo里的话，MainActivity408行.bitrate（）里面你可以提供更小的参数来进行压缩

**Comment by yellowcath** [comment]
不同的GPU能处理的尺寸上线是不一样的

**Comment by AimersCat** [comment]
看日志没有错误信息，不会crash, 还有个问题是这个压缩的效率和那些因素有关呢？ 比特率？ 视频分辨率？
手机GPU ？

**Comment by yellowcath** [comment]
首先是硬件，gpu、cpu都有影响，然后视频本身的话就是分辨率和比特率越高压缩越慢
